spring:
  datasource:
    url: jdbc:postgresql://localhost:4003/primes
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialext.PostgreSQLDialect

  sql:
    init:
      mode: always

  server:
    port: 8005
